### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by emid** [Tschucker/ArduinoBLE-Cycle-Power-Service#1]
Thanks for your ArduinoBKE-Cycle-Power-Service, really great idea.
I am trying to compile for a new Nano 33 BLE Sense and I always get the same error:

In file included from /Users/xxxx/Downloads/ArduinoBLE-Cycle-Power-Service-master/blecyclepower/blecyclepower.ino:5:0:
/Users/xxxx/Documents/Arduino/libraries/Nano33BLESensor/src/Nano33BLEMagnetic.h:89:7: error: 'osPriority' has not been declared
       osPriority threadPriority = osPriorityNormal,
       ^~~~~~~~~~

Any idea?

**Comment by Tschucker** [comment]
Check to make sure you can run one of the examples from https://github.com/DaleGia/Nano33BLESensor since it uses MBedOS on the device

**Comment by emid** [comment]
Thanks. The same error with all the examples. 
It seems that more people are having exactly the same problem compiling for BLE 33 sense:
https://forum.arduino.cc/t/what-has-been-changed-in-ble-33-sense-cannot-compile-after-purchase-new-ble-33/880934/3

**Comment by Tschucker** [comment]
did you try installing the deprecated package Arduino Mbed OS boards package version 1.1.6? That is what I have installed.

**Comment by emid** [comment]
Now it compiles perfectly. Installing deprecated package Arduino Mbed OS boards package version 1.1.6 resolved the problem.
Before doing that, I discovered that the problem was related to sensor libraries. When lines related to magnetometer were commented out, it compiled with the new Mbed OS 2.4.1. 
I really appreciate your help as I am new to arduino nano 33 BLE sense! Thanks again for this great software
